### ISSUE TITLE
Auth#verifyIdToken always throws unimplemented error

### ISSUE THREAD

**Issue by zacharypuulsedev** [invertase/dart_firebase_admin#20]
Version 0.3.0

I know it's an early build, so just drawing attention to a blocking feature for wider adoption. We use `verifyIdToken` to verify requests from clients before performing requests using admin functionality or firestore. 

Unfortunately, I don't have enough familiarity with the jwt spec and library design to understand what the `jwtKey` and other missing params are at `src/utils/jwt.dart:100`.

Issue:
Auth#verifyIdToken always throws unimplemented error.

Reproduce:
```
final FirebaseAdminApp admin =  await FirebaseAdminInitialization(container).initialize();
final auth = Auth(admin);
final idToken = await auth.verifyIdToken(jwt);
await admin.close();
```

StackTrace:
```
#0      PublicKeySignatureVerifier.verify (package:dart_firebase_admin/src/utils/jwt.dart:100)
#1      FirebaseTokenVerifier._verifySignature (package:dart_firebase_admin/src/auth/token_verifier.dart:119)
#2      FirebaseTokenVerifier._decodeAndVerify (package:dart_firebase_admin/src/auth/token_verifier.dart:101)
<asynchronous suspension>
#3      FirebaseTokenVerifier.verifyJWT (package:dart_firebase_admin/src/auth/token_verifier.dart:76)
<asynchronous suspension>
#4      _BaseAuth.verifyIdToken (package:dart_firebase_admin/src/auth/base_auth.dart:360)
```

**Comment by niklasbartsch** [comment]
You are not alone ➕

**Comment by niklasbartsch** [comment]
@zacharypuulsedev does it work with a different version?

**Comment by zacharypuulsedev** [comment]
> @zacharypuulsedev does it work with a different version?
From this v0.2 commit, it's not implemented there

**Comment by rrousselGit** [comment]
I'll look into it. Looks like an oversight

**Comment by markbreuss** [comment]
This Feature is blocking us as well to use this package at the Moment. We would also be open to sponsorship if this helps someone to dedicate more time on this.

**Comment by guccisekspir** [comment]
<img width="1115" alt="image" src="https://github.com/invertase/dart_firebase_admin/assets/56968218/d78bfff5-a917-4449-8eda-4009e616df21">
same

**Comment by Fraa-124** [comment]
@rrousselGit, this issue and #16 are preventing the use of the Firebase Admin Dart package.

**Comment by oikkoikk** [comment]
I was wondering if there has been any progress or if there are any planned actions.

**Comment by labrom** [comment]
Should the verifyIdToken check mark be removed from the README in the meantime?

**Comment by lukepighetti** [comment]
> Should the verifyIdToken check mark be removed from the README in the meantime?

https://github.com/invertase/dart_firebase_admin/pull/53

**Comment by lukepighetti** [comment]
I'm using this for now https://github.com/mtwichel/validate-firebase-auth-dart/blob/main/lib/src/validate_firebase_auth.dart

has the added benefit of not needing a service account json file. just the project id

```dart
import 'package:sep_server/di.dart';
import 'package:validate_firebase_auth/validate_firebase_auth.dart';

class AuthService {
  Future<bool> tokenValid(String? token) async {
    if (token == null) return false;
    final validator = FirebaseAuthValidator();
    await validator.init(projectId: di.config.fbProjectId);
    final idToken = await validator.validate(token);
    return !idToken.expired;
  }
}

extension on IdToken {
  DateTime get looseExpiry => claims.expiry.add(Duration(hours: 6));
  bool get expired => DateTime.now().isAfter(looseExpiry);
}
```
