### ISSUE TITLE
FirebaseMessagingAdminException: messaging/unknown: Unknown error occurred.

### ISSUE THREAD

**Issue by kmcgill88** [invertase/dart_firebase_admin#22]
I'm getting this error when using `Messaging.send`. I believe I've narrowed it down to that this is happening when attempting to send a message to a stale FCM token. 'active' tokens do not throw the exception.

I'm migrating some things from JS to Dart. I see you have some TS files committed as well. Could this potentially be related to [detect-invalid-token-responses-from-the-fcm-backend](https://firebase.google.com/docs/cloud-messaging/manage-tokens#detect-invalid-token-responses-from-the-fcm-backend)?

**Comment by kmcgill88** [comment]
`Requested entity was not found.` Looks like my hunch was correct. The message returned from FCM isn't matching up with `MessagingClientErrorCode`. It looks like [ErrorCodes](https://firebase.google.com/docs/reference/fcm/rest/v1/ErrorCode) were followed for the enum name however I wonder if the HTTP status code would be a more reliable approach.

```dart
  unregistered(
    code: 'UNREGISTERED',
    'App instance was unregistered from FCM. '
    'This usually means that the token used is no longer valid and a new one must be used.',
  ),
```

<img width="737" alt="image" src="https://github.com/invertase/dart_firebase_admin/assets/1992370/fa3b3ba3-a02c-4db9-af2f-0e722c95c35b">

<img width="520" alt="image" src="https://github.com/invertase/dart_firebase_admin/assets/1992370/ed6cae9a-3a2a-4c60-b195-359815987f47">

If you agree with the HTTP approach to mapping back to`MessagingClientErrorCode` we can easily pull the http status code from the `DetailedApiRequestError` here.

```dart
  @internal
  factory FirebaseMessagingAdminException.fromServerError(
    fmc1.DetailedApiRequestError error,
  ) {
    return FirebaseMessagingAdminException(
      MessagingClientErrorCode.fromCode(error.message),
    );
  }```

If you agree or have a better idea I'm happy to contribute!

**Comment by rrousselGit** [comment]
> If you agree or have a better idea I'm happy to contribute!

Sure, that sounds good :)

**Comment by rrousselGit** [comment]
Coming back to this: HTTP codes aren't a good approach I think.
We should rely on that "status" key. Some errors may have the same http code, but a different status

**Comment by kmcgill88** [comment]
This is what confused me to begin with. I don't believe Firebase responses match their docs. `status` from the screenshot above for a stale/expired FCM token was `NOT_FOUND` however both docs below state it should be`UNREGISTERED` (HTTP error code = 404). As a result, I kept getting a generic error and did not know how to recover. 

[detect-invalid-token-responses-from-the-fcm-backend](https://firebase.google.com/docs/cloud-messaging/manage-tokens#detect-invalid-token-responses-from-the-fcm-backend) and [ErrorCode](https://firebase.google.com/docs/reference/fcm/rest/v1/ErrorCode)

> Some errors may have the same http code, but a different status

I'm not seeing that in the docs?

**Comment by rrousselGit** [comment]
I'll come back to you in a bit. I need to look again into how the JS SDK was implemented. This implementation is based on it after-all.

You do make a point. The doc you linked does show a corelation with the http code. I remember using a different doc, but maybe I picked the wrong one.
I'll double check and re-evaluate this.

**Comment by rrousselGit** [comment]
I see the problem now. There are a few mismatches with the JS variant, and some bugs.
I'll update those myself.
