### ISSUE TITLE
FirebaseFirestoreAdminException - unable to authenticate 

### ISSUE THREAD

**Issue by niklasbartsch** [invertase/dart_firebase_admin#3]
I downloaded the `service-account.json` file and put it into my root folder of my dart_frog project.

I use a custom `main.dart` file. For now I put the initialization into the run function to test my setup.

```
Future<HttpServer> run(Handler handler, InternetAddress ip, int port) async {

  final credentials =
      Credential.fromServiceAccount(File('service-account.json'));
 
  final admin = FirebaseAdminApp.initializeApp(
    'projectName',
    credentials,
  );

  final firestore = Firestore(admin);

  await firestore
      .doc('{collection}/{id}')
      .get();
  
  return serve(handler, ip, port);
}

```
I get the following error on Data Fetching

`FirebaseFirestoreAdminException: firestore/unknown: No error details. HTTP status was: 404. null`

Am I missing something?

**Comment by rrousselGit** [comment]
Oopsy, fixed

**Comment by niklasbartsch** [comment]
Thank you so much! Works like a charm
