### ISSUE TITLE
is Realtime update available in this library for Firestore?

### ISSUE THREAD

**Issue by SahajRana** [invertase/dart_firebase_admin#47]
Hi Team,

I'm looking for Realtime update in Firestore. Can it be done?

**Comment by rrousselGit** [comment]
We lack streaming API. So no

It's in the readme that `.snapshots()` and some other APIs aren't supported

**Comment by mafreud** [comment]
@rrousselGit Hi, will .snapshot() be supported in the future?

**Comment by mafreud** [comment]
@rrousselGit Are you going to support streaming API?

**Comment by rrousselGit** [comment]
Depends on if the internal API ever get streaming support.
I don't have control over it. Google does
