### ISSUE TITLE
Release Request

### ISSUE THREAD

**Issue by KKimj** [invertase/dart_firebase_admin#49]
Hello,

I would like to request the release of the next version with the Timestamp Constructor feature.

Thank you for considering my request!

Thanks,

**Comment by markbreuss** [comment]
any update on the release?

**Comment by rrousselGit** [comment]
Done

**Comment by KKimj** [comment]
@rrousselGit 

Hi! I can't find version 0.4.0 on pub.dev.
Could you please check? Thank you!

https://pub.dev/packages/dart_firebase_admin/changelog
